# File: docker-compose.yml
# Author: Matus Remen (xremen01@stud.fit.vutbr.cz)
# Date: 2023-03-15
# Description: Docker compose file for CloneGuard, contains all services and their configuration.

version: '3.9'

volumes:
  # legacy name
  coinwatch_data:

services:
  db:
    image: postgres:14
    volumes:
      - coinwatch_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    logging:
      driver: none
    environment:
      - REDIS_SAVE=
      - REDIS_APPENDONLY=no
    ports:
      - 6379:6379

  worker:
    image: app
    command: python3 -m cloneguard.worker
    volumes:
      - .:/app
    build:
      context: .
    environment:
      DB_NAME: postgres
      PG_USER: admin
      PG_PASS: postgres
      PG_HOST: host.docker.internal
      PG_PORT: 5432
    env_file:
      - ./cloneguard/.env
    depends_on:
      - db
      - redis

  api:
    image: app
    command: uvicorn cloneguard.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    build:
      context: .
    environment:
      DB_NAME: postgres
      PG_USER: admin
      PG_PASS: postgres
      PG_HOST: host.docker.internal
      PG_PORT: 5432
    env_file:
      - ./cloneguard/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - worker
