version: '3.4'

volumes:
  coinwatch_data:

services:
  db:
    image: postgres:14
    volumes:
      - coinwatch_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  app:
    image: app
    command: echo "Hello"
    volumes:
      - .:/app
    build:
      context: .
    environment:
      DB_NAME: postgres
      PG_USER: admin
      PG_PASS: postgres
      PG_HOST: host.docker.internal
      PG_PORT: 5432
    env_file:
      - ./coinwatch/.env
    depends_on:
      - db
