version: '3.9'

volumes:
  coinwatch_data:

services:
  db:
    image: postgres:14
    volumes:
      - coinwatch_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    logging:
      driver: none
    ports:
      - 6379:6379

  worker:
    image: app
    command: python3 -m coinwatch.worker
    volumes:
      - .:/app
    build:
      context: .
    environment:
      DB_NAME: postgres
      PG_USER: admin
      PG_PASS: postgres
      PG_HOST: host.docker.internal
      PG_PORT: 5432
    env_file:
      - ./coinwatch/.env
    depends_on:
      - db
      - redis

  api:
    image: app
    command: uvicorn coinwatch.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    build:
      context: .
    environment:
      DB_NAME: postgres
      PG_USER: admin
      PG_PASS: postgres
      PG_HOST: host.docker.internal
      PG_PORT: 5432
    env_file:
      - ./coinwatch/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - worker
